#! /bin/bash

# If running from an extracted image, then export ARGV0 and APPDIR
if [ -z "${APPIMAGE}" ]; then
    EXEPATH=`realpath $0`
    export APPDIR=`dirname $EXEPATH`
    export ARGV0="$0"
fi

# Resolve the calling command (preserving symbolic links).
export APPIMAGE_COMMAND=$(command -v -- "$ARGV0")

# Call python to run snappy.app
if [ $# == 1 ] && [ $1 == --install ]; then
    if [ -z "${APPIMAGE}" ]; then
	echo "The --install option requires a packed AppImage."
	exit 1
    fi
    if [ -z "${XDG_DATA_HOME}" ]; then
	XDG_DATA_HOME="$HOME/.local/share"
    fi
    mkdir -p "${XDG_DATA_HOME}/applications"
    mkdir -p "${XDG_DATA_HOME}/icons"
    sed -e "s|Exec=.*|Exec=${APPIMAGE}|" "${APPDIR}/snappy.desktop" >"${XDG_DATA_HOME}/applications/snappy.desktop"
    cp "${APPDIR}/SnapPy.png" "${XDG_DATA_HOME}/icons"
else
    "${APPDIR}/bin/python3.13" -m snappy.app
fi



