name: Build SnapPy AppImage

on: [push, pull_request]

jobs:
  build_appimage:
    name: Build SnapPy AppImage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build AppImage
        run: |
          make

      - uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: ./SnapPy-x86_64.AppImage
